In [1]:
import numpy as np

In [2]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [3]:
b = np.array([[1,7,20], [5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [4]:
b.ndim  # Bu fonksiyon dizinin boyutunu öğrenmek için kullanılır

2

In [5]:
# Çok satır çok sütunlu dizi boyutu öğrenmek için shape kullanılır

b.shape

(2, 3)

In [7]:
a.dtype

dtype('int64')

In [8]:
# Dizideki belirli bir hücreye erişmek
print(b)
b[0,2]

[[ 1  7 20]
 [ 5  8  9]]


20

In [9]:
b[1,1]

8

In [10]:
b[0]

array([ 1,  7, 20])

In [12]:
# İlk satırdaki 2. ve 3. elemanlara (7 ve 20) erişmek için : kullanabiliriz

b[0, 1:]

array([ 7, 20])

In [13]:
b[1,1] = 18
b[1,1]

18

In [14]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

# Otomatik array oluşturma

In [15]:
# Tümü sıfır

dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# Tüm değerler aynı

dizi1 = np.full((4,4),50)  # Önce dizinin sütun satır sayısı, sonra içereceği veri
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [17]:
# Random dizi oluşturma

dizi2 = np.random.rand(4,3)
dizi2

array([[0.66175731, 0.98366257, 0.66965816],
       [0.3112012 , 0.55030741, 0.20247503],
       [0.49548208, 0.278909  , 0.76442497],
       [0.76918167, 0.80397559, 0.01944125]])

In [18]:
# Otomatik random int dizi

dizi3 = np.random.randint(0,100,size=(5,5))
dizi3

array([[57, 53, 18, 27, 45],
       [ 8, 64, 81, 95, 57],
       [13, 30, 39, 61, 48],
       [35, 88, 27,  6, 89],
       [20, 26, 33,  3, 54]])

In [19]:
# Dizi kopyalarken copy() fonksiyonunu kullanmak daha sağlıklı olur

a = np.array([1,2,3])
b = a.copy()
b[0] = 90
print(a)

[1 2 3]


# Array'de matematiksel işlemler

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a+4

array([5, 6, 7, 8])

In [22]:
a*2

array([2, 4, 6, 8])

In [23]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [24]:
a*2
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [25]:
a**2

array([ 1,  4,  9, 16])

# İstatistik

In [26]:
dizi4 = np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.min(dizi4)

1

In [28]:
np.max(dizi4)

6

In [29]:
np.sum(dizi4)

21

# Dosyadan dizi yükleme

In [32]:
filedata = np.genfromtxt("ornek.txt", delimiter=",")
filedata = filedata.astype("int32")
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [33]:
filedata[1,0]

8